### ISSUE TITLE
MY FRAMES 😢 

### ISSUE THREAD

**Issue by Crazyafk** [CoolerGangster/Create-Arcane-Engineering#14]
i have a new laptop with 16gb ram and a 13th gen intel i7. Yet when i have the game open it takes up 90%+ of these resources and i get about 5 fps. Any clue why the performance of this pack is so bad and what i can do about it?

**Comment by HarlanJ** [comment]
If your laptop has a dedicated GPU, you may need to manually configure your graphics drivers to be used for Minecraft. You can also turn off shaders, which should help immensely.

**Comment by Crazyafk** [comment]
yeah, it was trying to run on integrated graphics lol. classic error
