### ISSUE TITLE
Reward of Patience enchanted books are useless.

### ISSUE THREAD

**Issue by MrLar** [CoolerGangster/Create-Arcane-Engineering#18]
The loot table for the patience loot assigns enchantments to `minecraft:enchanted_book` using `enchant_with_levels` this however does not make the books store the entchantments but rather *actually* enchants them with it (for instance a silk touch book could actually obtain grass when breaking it with the book). I believe the correct way is to use `minecraft:book` as a base item instead of `minecraft:enchanted_book`, as the function `enchant_with_levels` mimicks an enchanting table.

**Comment by derram** [comment]
Guessing this is why I got an "Enchanted book" as a reward from one of the loot boxes. 

No actual enchant, just "Enchanted book"
