### ISSUE TITLE
Iron shovel recipe conflicts

### ISSUE THREAD

**Issue by Hexasphere0** [CoolerGangster/Create-Arcane-Engineering#2]
You can't currently make an iron shovel because it conflicts with the alloy scanner recipe.

**Comment by NekoSpirits** [comment]
![javaw_276OuWJBy9](https://github.com/CoolerGangster/Create-Arcane-Engineering/assets/20034469/ac519b61-2281-432f-972d-d66b208b6eb1)

You should be able to hit this button to switch between recipe conflicts.

**Comment by Hexasphere0** [comment]
Oh bruh I didn't realize that button exists

**Comment by NekoSpirits** [comment]
Can this be closed out? the lastest release changes the recipe to be 4 sticks.
