### ISSUE TITLE
Crash caused by Create: Steam 'n' Rails

### ISSUE THREAD

**Issue by ControlNet** [CoolerGangster/Create-Arcane-Engineering#24]
As mentioned by https://github.com/Layers-of-Railways/Railway/issues/225. The current version (also the latest version) of _Create: Steam 'n' Rails_ used in the modpack `0.1.7` is not compatible with _Create_ `0.5.1c`. When placing a train on a monorail, the game will crash.

I suggest to fallback the version of following mods before it's fixed.
- _create_ to `0.5.1b`.
- _compressedcreativity_ to `0.1.6`, due to dependencies.

**Comment by derram** [comment]
Seems to be just trains in general. 

I crash instantly if I go near my train in 0.1.7, and there's no monorail involved.

**Comment by quasiqubed** [comment]
Create: Steam n Rails has released an update this week seemly updating to use 0.5.1c.

**Comment by derram** [comment]
Swapped out to the newer version in the 0.1.7 install and no more crash when approaching the train.

Still no monorail to test tho.
