### ISSUE TITLE
Superflats do not generate

### ISSUE THREAD

**Issue by darkshadow543** [CoolerGangster/Create-Arcane-Engineering#48]
Version: 0.1.7

Extra Mods: none

How to replicate:

1. Go to world generation
2. Go to world options
3. Set to superflat (preset does not matter, tried several)
4. Generate world
5. World that is generated is a normal world, not a superflat world.

I usually generate superflats when playing packs to build small building or play around in creative mode for inspiration.  I was going to go build a farm idea for berry farming when I ran into this bug.

**Comment by willownezz** [comment]
I believe that is a mod issue 'terralith', you can remove it and create your superflat world than add it back.

**Comment by darklotus781** [comment]
Yep, this is not a modpack issue
