### ISSUE TITLE
Everything in The Trade Market costs 10 Silver.

### ISSUE THREAD

**Issue by Narwhalian** [CoolerGangster/Create-Arcane-Engineering#74]
![image](https://github.com/CoolerGangster/Create-Arcane-Engineering/assets/60676712/8468d514-feed-4e4a-aaa3-24841f1feb92)

**Comment by Epicificator** [comment]
no, those are the prices for the TRADE CARDS. not the prices of the actual items.

**Comment by Narwhalian** [comment]
Ohhh, I see. Thank you. My bad lol
